// Dr. Media Dashboard - Layer 3 Frontend Cache Test File
// This is a test to verify large file uploads work via MCP tool
// File size: approximately 10KB of content
// Generated by the cache implementation task

var TEST_CACHE_LARGE_CONTENT = true;
var TEST_LINES = [
  "Line 1 of test content for large file upload verification",
  "Line 2 of test content for large file upload verification",
  "Line 3 of test content for large file upload verification",
  "Line 4 of test content for large file upload verification",
  "Line 5 of test content for large file upload verification"
];
